"""Statischer Seed-Datensatz, 1:1 aus dem HTML-Prototyp (breakpoint-dashboard.html)
übernommen: TACTIC_GROUPS, KB und TACTIC_DEFAULTS. Wird nur in Schritt 1/2 als
Bootstrap-Datensatz genutzt — ab Schritt 6 übernimmt der admin-gesteuerte
STIX-Import (docs/projektauftrag.md Abschnitt 6a.2) die Pflege des Katalogs.
"""

# Reihenfolge entspricht der offiziellen MITRE-Enterprise-Kill-Chain (1-14) und
# damit auch der Reihenfolge, in der TACTIC_GROUPS im Prototyp deklariert ist.
TACTIC_GROUPS: dict[str, list[tuple[str, str]]] = {
    "Reconnaissance": [
        ("T1595", "Active Scanning"),
        ("T1592", "Gather Victim Host Information"),
        ("T1589", "Gather Victim Identity Information"),
        ("T1590", "Gather Victim Network Information"),
        ("T1591", "Gather Victim Org Information"),
        ("T1598", "Phishing for Information"),
        ("T1597", "Search Closed Sources"),
        ("T1596", "Search Open Technical Databases"),
        ("T1593", "Search Open Websites/Domains"),
        ("T1594", "Search Victim-Owned Websites"),
    ],
    "Resource Development": [
        ("T1583", "Acquire Infrastructure"),
        ("T1586", "Compromise Accounts"),
        ("T1584", "Compromise Infrastructure"),
        ("T1587", "Develop Capabilities"),
        ("T1585", "Establish Accounts"),
        ("T1588", "Obtain Capabilities"),
        ("T1608", "Stage Capabilities"),
    ],
    "Initial Access": [
        ("T1189", "Drive-by Compromise"),
        ("T1190", "Exploit Public-Facing Application"),
        ("T1133", "External Remote Services"),
        ("T1200", "Hardware Additions"),
        ("T1566", "Phishing"),
        ("T1566.001", "Phishing: Spearphishing Attachment"),
        ("T1091", "Replication Through Removable Media"),
        ("T1195", "Supply Chain Compromise"),
        ("T1199", "Trusted Relationship"),
        ("T1078", "Valid Accounts"),
    ],
    "Execution": [
        ("T1059", "Command and Scripting Interpreter"),
        ("T1059.001", "Command and Scripting Interpreter: PowerShell"),
        ("T1609", "Container Administration Command"),
        ("T1610", "Deploy Container"),
        ("T1203", "Exploitation for Client Execution"),
        ("T1559", "Inter-Process Communication"),
        ("T1106", "Native API"),
        ("T1053", "Scheduled Task/Job"),
        ("T1129", "Shared Modules"),
        ("T1072", "Software Deployment Tools"),
        ("T1569", "System Services"),
        ("T1204", "User Execution"),
        ("T1047", "Windows Management Instrumentation"),
    ],
    "Persistence": [
        ("T1098", "Account Manipulation"),
        ("T1547", "Boot or Logon Autostart Execution"),
        ("T1037", "Boot or Logon Initialization Scripts"),
        ("T1176", "Browser Extensions"),
        ("T1554", "Compromise Client Software Binary"),
        ("T1136", "Create Account"),
        ("T1543", "Create or Modify System Process"),
        ("T1546", "Event Triggered Execution"),
        ("T1133", "External Remote Services"),
        ("T1574", "Hijack Execution Flow"),
        ("T1525", "Implant Internal Image"),
        ("T1556", "Modify Authentication Process"),
        ("T1137", "Office Application Startup"),
        ("T1542", "Pre-OS Boot"),
        ("T1053", "Scheduled Task/Job"),
        ("T1505", "Server Software Component"),
        ("T1078", "Valid Accounts"),
    ],
    "Privilege Escalation": [
        ("T1548", "Abuse Elevation Control Mechanism"),
        ("T1134", "Access Token Manipulation"),
        ("T1547", "Boot or Logon Autostart Execution"),
        ("T1037", "Boot or Logon Initialization Scripts"),
        ("T1543", "Create or Modify System Process"),
        ("T1484", "Domain or Tenant Policy Modification"),
        ("T1611", "Escape to Host"),
        ("T1546", "Event Triggered Execution"),
        ("T1068", "Exploitation for Privilege Escalation"),
        ("T1574", "Hijack Execution Flow"),
        ("T1055", "Process Injection"),
        ("T1053", "Scheduled Task/Job"),
        ("T1078", "Valid Accounts"),
    ],
    "Defense Evasion": [
        ("T1548", "Abuse Elevation Control Mechanism"),
        ("T1134", "Access Token Manipulation"),
        ("T1197", "BITS Jobs"),
        ("T1140", "Deobfuscate/Decode Files or Information"),
        ("T1006", "Direct Volume Access"),
        ("T1484", "Domain or Tenant Policy Modification"),
        ("T1480", "Execution Guardrails"),
        ("T1211", "Exploitation for Defense Evasion"),
        ("T1222", "File and Directory Permissions Modification"),
        ("T1564", "Hide Artifacts"),
        ("T1574", "Hijack Execution Flow"),
        ("T1562", "Impair Defenses"),
        ("T1070", "Indicator Removal"),
        ("T1202", "Indirect Command Execution"),
        ("T1036", "Masquerading"),
        ("T1556", "Modify Authentication Process"),
        ("T1578", "Modify Cloud Compute Infrastructure"),
        ("T1112", "Modify Registry"),
        ("T1601", "Modify System Image"),
        ("T1599", "Network Boundary Bridging"),
        ("T1027", "Obfuscated Files or Information"),
        ("T1542", "Pre-OS Boot"),
        ("T1055", "Process Injection"),
        ("T1207", "Rogue Domain Controller"),
        ("T1014", "Rootkit"),
        ("T1218", "System Binary Proxy Execution"),
        ("T1216", "System Script Proxy Execution"),
        ("T1221", "Template Injection"),
        ("T1127", "Trusted Developer Utilities Proxy Execution"),
        ("T1535", "Unused/Unsupported Cloud Regions"),
        ("T1550", "Use Alternate Authentication Material"),
        ("T1078", "Valid Accounts"),
        ("T1078.004", "Valid Accounts: Cloud Accounts"),
        ("T1497", "Virtualization/Sandbox Evasion"),
        ("T1220", "XSL Script Processing"),
    ],
    "Credential Access": [
        ("T1557", "Adversary-in-the-Middle"),
        ("T1110", "Brute Force"),
        ("T1555", "Credentials from Password Stores"),
        ("T1212", "Exploitation for Credential Access"),
        ("T1187", "Forced Authentication"),
        ("T1606", "Forge Web Credentials"),
        ("T1056", "Input Capture"),
        ("T1556", "Modify Authentication Process"),
        ("T1111", "Multi-Factor Authentication Interception"),
        ("T1621", "Multi-Factor Authentication Request Generation"),
        ("T1040", "Network Sniffing"),
        ("T1003", "OS Credential Dumping"),
        ("T1528", "Steal Application Access Token"),
        ("T1558", "Steal or Forge Kerberos Tickets"),
        ("T1539", "Steal Web Session Cookie"),
        ("T1552", "Unsecured Credentials"),
    ],
    "Discovery": [
        ("T1087", "Account Discovery"),
        ("T1010", "Application Window Discovery"),
        ("T1217", "Browser Information Discovery"),
        ("T1580", "Cloud Infrastructure Discovery"),
        ("T1538", "Cloud Service Dashboard"),
        ("T1526", "Cloud Service Discovery"),
        ("T1619", "Cloud Storage Object Discovery"),
        ("T1613", "Container and Resource Discovery"),
        ("T1482", "Domain Trust Discovery"),
        ("T1083", "File and Directory Discovery"),
        ("T1046", "Network Service Discovery"),
        ("T1135", "Network Share Discovery"),
        ("T1201", "Password Policy Discovery"),
        ("T1120", "Peripheral Device Discovery"),
        ("T1069", "Permission Groups Discovery"),
        ("T1057", "Process Discovery"),
        ("T1012", "Query Registry"),
        ("T1018", "Remote System Discovery"),
        ("T1518", "Software Discovery"),
        ("T1082", "System Information Discovery"),
        ("T1614", "System Location Discovery"),
        ("T1016", "System Network Configuration Discovery"),
        ("T1049", "System Network Connections Discovery"),
        ("T1033", "System Owner/User Discovery"),
        ("T1007", "System Service Discovery"),
        ("T1124", "System Time Discovery"),
        ("T1497", "Virtualization/Sandbox Evasion"),
    ],
    "Lateral Movement": [
        ("T1210", "Exploitation of Remote Services"),
        ("T1534", "Internal Spearphishing"),
        ("T1570", "Lateral Tool Transfer"),
        ("T1563", "Remote Service Session Hijacking"),
        ("T1021", "Remote Services"),
        ("T1021.001", "Remote Services: Remote Desktop Protocol"),
        ("T1080", "Taint Shared Content"),
        ("T1550", "Use Alternate Authentication Material"),
    ],
    "Collection": [
        ("T1557", "Adversary-in-the-Middle"),
        ("T1560", "Archive Collected Data"),
        ("T1123", "Audio Capture"),
        ("T1119", "Automated Collection"),
        ("T1185", "Browser Session Hijacking"),
        ("T1115", "Clipboard Data"),
        ("T1530", "Data from Cloud Storage"),
        ("T1602", "Data from Configuration Repository"),
        ("T1213", "Data from Information Repositories"),
        ("T1005", "Data from Local System"),
        ("T1039", "Data from Network Shared Drive"),
        ("T1025", "Data from Removable Media"),
        ("T1074", "Data Staged"),
        ("T1114", "Email Collection"),
        ("T1056", "Input Capture"),
        ("T1113", "Screen Capture"),
        ("T1125", "Video Capture"),
    ],
    "Command and Control": [
        ("T1071", "Application Layer Protocol"),
        ("T1092", "Communication Through Removable Media"),
        ("T1132", "Data Encoding"),
        ("T1001", "Data Obfuscation"),
        ("T1568", "Dynamic Resolution"),
        ("T1573", "Encrypted Channel"),
        ("T1008", "Fallback Channels"),
        ("T1105", "Ingress Tool Transfer"),
        ("T1104", "Multi-Stage Channels"),
        ("T1095", "Non-Application Layer Protocol"),
        ("T1571", "Non-Standard Port"),
        ("T1572", "Protocol Tunneling"),
        ("T1090", "Proxy"),
        ("T1219", "Remote Access Software"),
        ("T1205", "Traffic Signaling"),
        ("T1102", "Web Service"),
    ],
    "Exfiltration": [
        ("T1020", "Automated Exfiltration"),
        ("T1030", "Data Transfer Size Limits"),
        ("T1048", "Exfiltration Over Alternative Protocol"),
        ("T1041", "Exfiltration Over C2 Channel"),
        ("T1011", "Exfiltration Over Other Network Medium"),
        ("T1052", "Exfiltration Over Physical Medium"),
        ("T1567", "Exfiltration Over Web Service"),
        ("T1029", "Scheduled Transfer"),
        ("T1537", "Transfer Data to Cloud Account"),
    ],
    "Impact": [
        ("T1531", "Account Access Removal"),
        ("T1485", "Data Destruction"),
        ("T1486", "Data Encrypted for Impact"),
        ("T1565", "Data Manipulation"),
        ("T1491", "Defacement"),
        ("T1561", "Disk Wipe"),
        ("T1499", "Endpoint Denial of Service"),
        ("T1495", "Firmware Corruption"),
        ("T1490", "Inhibit System Recovery"),
        ("T1498", "Network Denial of Service"),
        ("T1496", "Resource Hijacking"),
        ("T1489", "Service Stop"),
        ("T1529", "System Shutdown/Reboot"),
    ],
}

# Die ~10 im Prototyp detailliert ausgearbeiteten Techniken (mapping_source='specific').
# 'tactic' ist hier nur eine Anzeige-Hilfe aus dem Prototyp (teils kombiniert, z.B.
# "Defense Evasion / Persistence") und wird beim Seeden NICHT als technique.tactic_id
# verwendet — maßgeblich ist die Platzierung in TACTIC_GROUPS (siehe seed.py).
KB: dict[str, dict] = {
    "T1566.001": {
        "name": "Phishing: Spearphishing Attachment",
        "capabilities": ["Email Security", "Security Awareness"],
        "prevent": ["E-Mail-Filterung / Sandboxing", "Attachment Detonation"],
        "detect": ["Phishing-Simulation Reporting", "Email Gateway Alerts"],
        "respond": ["Mailbox Quarantäne", "Zugangsdaten zurücksetzen"],
        "impact": "hoch",
        "effort": "niedrig",
    },
    "T1078": {
        "name": "Valid Accounts",
        "capabilities": ["MFA", "Conditional Access", "PAM", "Identity Monitoring"],
        "prevent": ["MFA erzwingen", "Conditional Access", "PAM"],
        "detect": ["Identity Threat Detection", "UEBA"],
        "respond": ["Account Disablement", "Session Revocation"],
        "impact": "sehr_hoch",
        "effort": "mittel",
    },
    "T1078.004": {
        "name": "Valid Accounts: Cloud Accounts",
        "capabilities": ["MFA", "Conditional Access", "PAM", "Cloud Identity Monitoring"],
        "prevent": ["MFA erzwingen", "Conditional Access", "PAM"],
        "detect": ["Cloud Identity Threat Detection", "UEBA"],
        "respond": ["Account Disablement", "Session Revocation"],
        "impact": "sehr_hoch",
        "effort": "mittel",
    },
    "T1021.001": {
        "name": "Remote Services: RDP",
        "capabilities": ["Network Segmentation", "PAM", "Endpoint Firewall"],
        "prevent": ["Microsegmentation", "RDP Gateway / Jump Host", "Direktes RDP deaktivieren"],
        "detect": ["Network Detection & Response", "Login Anomaly Detection"],
        "respond": ["Session Termination", "Netzwerk-Isolation"],
        "impact": "hoch",
        "effort": "niedrig",
    },
    "T1059.001": {
        "name": "Command & Scripting: PowerShell",
        "capabilities": ["Application Control", "Script Control", "EDR"],
        "prevent": ["Application Control", "Constrained Language Mode"],
        "detect": ["EDR", "PowerShell Logging", "SIEM-Korrelation"],
        "respond": ["Endpoint Isolation", "Process Termination"],
        "impact": "hoch",
        "effort": "mittel",
    },
    "T1003": {
        "name": "OS Credential Dumping",
        "capabilities": ["Credential Guard", "PAM", "EDR"],
        "prevent": ["Credential Guard", "LSASS-Schutz"],
        "detect": ["EDR", "Credential Access Alerts"],
        "respond": ["Zugangsdaten zurücksetzen", "Session Revocation"],
        "impact": "sehr_hoch",
        "effort": "mittel",
    },
    "T1055": {
        "name": "Process Injection",
        "capabilities": ["EDR", "Application Control"],
        "prevent": ["Exploit Protection", "Application Control"],
        "detect": ["EDR", "Behavioral Analytics"],
        "respond": ["Process Termination", "Endpoint Isolation"],
        "impact": "mittel",
        "effort": "mittel",
    },
    "T1486": {
        "name": "Data Encrypted for Impact",
        "capabilities": ["Backup & Recovery", "EDR", "Network Segmentation"],
        "prevent": ["Immutable Backups", "Application Control"],
        "detect": ["EDR", "File Integrity Monitoring"],
        "respond": ["Isolation", "Restore from Backup"],
        "impact": "sehr_hoch",
        "effort": "hoch",
    },
    "T1136": {
        "name": "Create Account",
        "capabilities": ["Identity Governance", "PAM"],
        "prevent": ["Least Privilege", "Approval Workflows"],
        "detect": ["Identity Monitoring", "Audit Logging"],
        "respond": ["Account Disablement"],
        "impact": "mittel",
        "effort": "niedrig",
    },
    "T1046": {
        "name": "Network Service Discovery",
        "capabilities": ["Network Segmentation", "Deception"],
        "prevent": ["Microsegmentation", "Port-Restriktionen"],
        "detect": ["Network Detection & Response", "Honeypots"],
        "respond": ["Netzwerk-Isolation"],
        "impact": "niedrig",
        "effort": "niedrig",
    },
}

# Taktik-Standardmapping: jede der 14 Taktiken bekommt eine Basis-Empfehlung, damit
# jede Technik ohne spezifisches KB-Mapping trotzdem eine Empfehlung bekommt.
TACTIC_DEFAULTS: dict[str, dict] = {
    "Reconnaissance": {
        "capabilities": ["Attack Surface Management", "Threat Intelligence"],
        "prevent": ["Digitale Angriffsfläche reduzieren", "Domain- / Brand-Monitoring"],
        "detect": ["Threat-Intelligence-Monitoring"],
        "respond": ["Takedown-Verfahren einleiten"],
        "impact": "niedrig",
        "effort": "niedrig",
    },
    "Resource Development": {
        "capabilities": ["Threat Intelligence"],
        "prevent": ["Externe Angriffsflächen minimieren"],
        "detect": ["Threat-Intelligence-Monitoring", "Infrastructure Tracking"],
        "respond": ["Takedown-Verfahren einleiten"],
        "impact": "niedrig",
        "effort": "niedrig",
    },
    "Initial Access": {
        "capabilities": ["Email Security", "MFA", "Application Control"],
        "prevent": ["E-Mail-Filterung", "MFA erzwingen", "Patch Management"],
        "detect": ["EDR", "Identity Monitoring"],
        "respond": ["Account Disablement", "Endpoint Isolation"],
        "impact": "hoch",
        "effort": "mittel",
    },
    "Execution": {
        "capabilities": ["Application Control", "Script Control", "EDR"],
        "prevent": ["Application Control", "Script Control"],
        "detect": ["EDR", "SIEM-Korrelation"],
        "respond": ["Process Termination", "Endpoint Isolation"],
        "impact": "hoch",
        "effort": "mittel",
    },
    "Persistence": {
        "capabilities": ["Identity Monitoring", "EDR", "PAM"],
        "prevent": ["Least Privilege", "PAM"],
        "detect": ["EDR", "Identity Monitoring"],
        "respond": ["Account Disablement", "Endpoint Isolation"],
        "impact": "mittel",
        "effort": "mittel",
    },
    "Privilege Escalation": {
        "capabilities": ["PAM", "Credential Guard", "EDR"],
        "prevent": ["Least Privilege", "Patch Management"],
        "detect": ["EDR", "Identity Monitoring"],
        "respond": ["Session Revocation", "Endpoint Isolation"],
        "impact": "hoch",
        "effort": "mittel",
    },
    "Defense Evasion": {
        "capabilities": ["EDR", "Application Control"],
        "prevent": ["Application Control", "Integrity Monitoring"],
        "detect": ["EDR", "File Integrity Monitoring"],
        "respond": ["Endpoint Isolation", "Process Termination"],
        "impact": "mittel",
        "effort": "mittel",
    },
    "Credential Access": {
        "capabilities": ["Credential Guard", "MFA", "PAM"],
        "prevent": ["Credential Guard", "MFA erzwingen"],
        "detect": ["Identity Monitoring", "EDR"],
        "respond": ["Zugangsdaten zurücksetzen", "Session Revocation"],
        "impact": "sehr_hoch",
        "effort": "mittel",
    },
    "Discovery": {
        "capabilities": ["Network Segmentation", "Deception", "Asset Visibility"],
        "prevent": ["Microsegmentation", "Least Privilege"],
        "detect": ["Deception / Honeypots", "Network Detection & Response"],
        "respond": ["Netzwerk-Isolation"],
        "impact": "niedrig",
        "effort": "niedrig",
    },
    "Lateral Movement": {
        "capabilities": ["Network Segmentation", "PAM", "Identity Monitoring"],
        "prevent": ["Microsegmentation", "PAM"],
        "detect": ["Network Detection & Response", "Identity Monitoring"],
        "respond": ["Session Termination", "Netzwerk-Isolation"],
        "impact": "hoch",
        "effort": "mittel",
    },
    "Collection": {
        "capabilities": ["Data Loss Prevention", "EDR"],
        "prevent": ["DLP-Policies", "Verschlüsselung sensibler Daten"],
        "detect": ["EDR", "DLP-Alerts"],
        "respond": ["Endpoint Isolation"],
        "impact": "mittel",
        "effort": "mittel",
    },
    "Command and Control": {
        "capabilities": ["Network Detection & Response", "Endpoint Firewall"],
        "prevent": ["Egress-Filterung", "Firewall-Policies"],
        "detect": ["Network Detection & Response", "DNS-Monitoring"],
        "respond": ["Netzwerk-Isolation", "C2-Infrastruktur blockieren"],
        "impact": "hoch",
        "effort": "mittel",
    },
    "Exfiltration": {
        "capabilities": ["Data Loss Prevention", "Network Detection & Response"],
        "prevent": ["DLP-Policies", "Egress-Filterung"],
        "detect": ["DLP-Alerts", "Network Detection & Response"],
        "respond": ["Netzwerk-Isolation", "Session Termination"],
        "impact": "sehr_hoch",
        "effort": "mittel",
    },
    "Impact": {
        "capabilities": ["Backup & Recovery", "EDR", "Network Segmentation"],
        "prevent": ["Immutable Backups", "Application Control"],
        "detect": ["EDR", "File Integrity Monitoring"],
        "respond": ["Isolation", "Restore from Backup"],
        "impact": "sehr_hoch",
        "effort": "hoch",
    },
}

# Masterliste aller Capabilities (ALL_CAPABILITIES aus dem Prototyp) — Quelle der
# Wahrheit für die capability-Tabelle, unabhängig davon, ob aktuell schon eine
# Portfolio-Technologie oder ein KB-Mapping darauf verweist.
ALL_CAPABILITIES: list[str] = [
    "Email Security", "Security Awareness", "MFA", "Conditional Access", "PAM",
    "Identity Monitoring", "Cloud Identity Monitoring", "Network Segmentation",
    "Endpoint Firewall", "Application Control", "Script Control", "EDR",
    "Credential Guard", "Backup & Recovery", "Identity Governance", "Deception",
    "Asset Visibility", "Attack Surface Management", "Threat Intelligence",
    "Data Loss Prevention", "Network Detection & Response",
]

# Kuratierter Mitigation->Capability/Control-Crosswalk für den MITRE-
# Mitigations-Bootstrap (docs/projektauftrag.md Abschnitt 6a.3/10e.2). Kein
# Admin-UI, lebt als Code-Liste (analog ALL_CAPABILITIES) und wird von einem
# Entwickler erweitert, wenn ein Import neue M-Nummern zeigt (Abschnitt 6a.3
# Punkt 7). Gegen die aktuelle MITRE-ATT&CK-Mitigations-Liste (44 aktuelle,
# nicht-deprecated M-Nummern, Stand dieser Session) geprüft — bewusst nicht
# vollständig: nicht jede Mitigation bildet sauber auf eine bestehende
# Capability ab (Abschnitt 6a.3 Punkt 3, z. B. reine Policy-/Prozess-
# Empfehlungen wie M1013 "Application Developer Guidance" oder MITRE-interne
# Platzhalter wie M1055 "Do Not Mitigate"/M1056 "Pre-compromise" bleiben
# absichtlich ungemappt).
#
# control_label ist absichtlich Deutsch und, wo sinnvoll, identisch mit einem
# bereits im Prototyp-KB verwendeten Control-Label (z. B. "MFA erzwingen",
# "PAM", "Application Control", "Credential Guard", "Microsegmentation",
# "Exploit Protection", "Patch Management", "Immutable Backups",
# "Conditional Access") — der Import erstellt dadurch keinen doppelten,
# englisch benannten Control-Zwilling, sondern hängt sich an dieselbe, von
# Menschen kuratierte Maßnahme an. Das verbessert die Kettenabdeckung direkt
# (mehr Techniken teilen sich denselben Control-Eintrag), statt nur den
# Katalog mit englischsprachigen Duplikaten aufzublähen.
# Wert je M-Nummer: {"control_label": str, "capabilities": list[str]}
MITIGATION_CROSSWALK: dict[str, dict] = {
    "M1015": {"control_label": "AD-Härtung", "capabilities": ["Identity Governance"]},
    "M1016": {"control_label": "Schwachstellen-Scanning", "capabilities": ["Attack Surface Management"]},
    "M1017": {"control_label": "Security-Awareness-Training", "capabilities": ["Security Awareness"]},
    "M1018": {"control_label": "Kontenverwaltung", "capabilities": ["Identity Governance"]},
    "M1019": {"control_label": "Threat-Intelligence-Programm", "capabilities": ["Threat Intelligence"]},
    "M1025": {"control_label": "LSASS-Schutz", "capabilities": ["Credential Guard"]},
    "M1026": {"control_label": "PAM", "capabilities": ["PAM"]},
    "M1027": {"control_label": "Passwort-Richtlinien", "capabilities": ["Identity Governance"]},
    "M1029": {"control_label": "Immutable Backups", "capabilities": ["Backup & Recovery"]},
    "M1030": {"control_label": "Microsegmentation", "capabilities": ["Network Segmentation"]},
    "M1031": {"control_label": "Netzwerk-Intrusion-Prevention", "capabilities": ["Network Detection & Response"]},
    "M1032": {"control_label": "MFA erzwingen", "capabilities": ["MFA"]},
    "M1033": {"control_label": "Application Control", "capabilities": ["Application Control"]},
    "M1035": {"control_label": "Microsegmentation", "capabilities": ["Network Segmentation"]},
    "M1036": {"control_label": "Conditional Access", "capabilities": ["Conditional Access"]},
    "M1037": {"control_label": "Endpoint-Firewall-Regeln", "capabilities": ["Endpoint Firewall"]},
    "M1038": {"control_label": "Application Control", "capabilities": ["Application Control"]},
    "M1040": {"control_label": "Verhaltensbasierte Endpoint-Prävention (EDR)", "capabilities": ["EDR"]},
    "M1041": {"control_label": "Verschlüsselung sensibler Daten", "capabilities": ["Data Loss Prevention"]},
    "M1042": {"control_label": "Angriffsfläche reduzieren", "capabilities": ["Attack Surface Management"]},
    "M1043": {"control_label": "Credential Guard", "capabilities": ["Credential Guard"]},
    "M1044": {"control_label": "Application Control", "capabilities": ["Application Control"]},
    "M1045": {"control_label": "Code-Signing-Pflicht", "capabilities": ["Application Control"]},
    "M1048": {"control_label": "Application Isolation / Sandboxing", "capabilities": ["EDR"]},
    "M1049": {"control_label": "Antivirus / Antimalware", "capabilities": ["EDR"]},
    "M1050": {"control_label": "Exploit Protection", "capabilities": ["EDR"]},
    "M1051": {"control_label": "Patch Management", "capabilities": ["Attack Surface Management"]},
    "M1052": {"control_label": "PAM", "capabilities": ["PAM"]},
    "M1053": {"control_label": "Immutable Backups", "capabilities": ["Backup & Recovery"]},
    "M1057": {"control_label": "DLP-Kontrollen", "capabilities": ["Data Loss Prevention"]},
    # M1020 SSL/TLS Inspection, M1021 Restrict Web-Based Content,
    # M1022 Restrict File and Directory Permissions,
    # M1024 Restrict Registry Permissions, M1034 Limit Hardware Installation,
    # M1039 Environment Variable Permissions, M1046 Boot Integrity,
    # M1047 Audit, M1060 Out-of-Band Communications Channel: bewusst nicht
    # gemappt — keine bestehende Capability bildet das sauber ab.
    # M1013 Application Developer Guidance, M1028 Operating System
    # Configuration, M1054 Software Configuration: reine Prozess-/Policy-
    # Empfehlungen ohne Technologie-Bezug (Abschnitt 6a.3 Punkt 3).
    # M1055 Do Not Mitigate, M1056 Pre-compromise: MITRE-Platzhalterwerte,
    # keine echten Mitigations.
}
