"""add technique_import_batch, technique deprecated/stix_id

Revision ID: 1c6c10890260
Revises: 9455f62dd07c
Create Date: 2026-08-31 12:10:32.747376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c6c10890260'
down_revision: Union[str, Sequence[str], None] = '9455f62dd07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technique_import_batch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Enum('GITHUB_RAW', 'TAXII', 'MANUAL_UPLOAD', name='import_source'), nullable=False),
    sa.Column('source_ref', sa.String(length=256), nullable=True),
    sa.Column('bundle_version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('DIFF_PENDING', 'DIFF_READY', 'APPLIED', 'ROLLED_BACK', 'FAILED', name='import_batch_status'), nullable=False),
    sa.Column('triggered_by', sa.String(length=128), nullable=True),
    sa.Column('diff_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pre_apply_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'technique',
        sa.Column('deprecated', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('technique', 'deprecated', server_default=None)
    op.add_column('technique', sa.Column('stix_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_technique_stix_id', 'technique', ['stix_id'])
    # ### end Alembic commands ###

    # mapping_source ist ein nativer Postgres-ENUM (Abschnitt 6a.3 Punkt 4 /
    # 10e Punkt 7) — ein neuer Wert lässt sich nicht per ALTER TABLE ändern,
    # sondern nur per ALTER TYPE ... ADD VALUE, und das läuft in Postgres
    # außerhalb einer Transaktion (der neue Wert darf in derselben
    # Transaktion, in der er hinzugefügt wird, noch nicht verwendet werden).
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE mapping_source ADD VALUE IF NOT EXISTS 'MITRE_DERIVED'")


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres kennt kein ALTER TYPE ... DROP VALUE — der 'MITRE_DERIVED'-Wert
    # bleibt im Enum-Typ bestehen, auch nach einem Downgrade. Unkritisch,
    # solange keine Zeile ihn tatsächlich verwendet (das würde ein Downgrade
    # ohnehin verhindern, da FK/Enum-Constraints das nicht zulassen).
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technique', 'stix_id')
    op.drop_column('technique', 'deprecated')
    op.drop_table('technique_import_batch')
    # ### end Alembic commands ###

    # op.drop_table() droppt bei Postgres nicht automatisch die für die
    # Spalten verwendeten nativen ENUM-Typen — sonst blieben sie als
    # verwaiste Typen zurück und ein erneutes upgrade() würde mit
    # "type already exists" fehlschlagen (in dieser Session so aufgetreten).
    sa.Enum(name='import_batch_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='import_source').drop(op.get_bind(), checkfirst=True)
