"""initial schema: tactic, technique, capability, control, mappings

Revision ID: 878a7946dccd
Revises: 
Create Date: 2026-08-29 10:35:22.051398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878a7946dccd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('control',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Enum('PREVENT', 'DETECT', 'RESPOND', name='control_category'), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'label', name='uq_control_category_label')
    )
    op.create_table('tactic',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('mitre_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mitre_order'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tactic_default_mapping',
    sa.Column('tactic_id', sa.String(length=64), nullable=False),
    sa.Column('impact', sa.Enum('NIEDRIG', 'MITTEL', 'HOCH', 'SEHR_HOCH', name='impact_level'), nullable=False),
    sa.Column('effort', sa.Enum('NIEDRIG', 'MITTEL', 'HOCH', name='effort_level'), nullable=False),
    sa.ForeignKeyConstraint(['tactic_id'], ['tactic.id'], ),
    sa.PrimaryKeyConstraint('tactic_id')
    )
    op.create_table('technique',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('tactic_id', sa.String(length=64), nullable=False),
    sa.Column('parent_technique_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['parent_technique_id'], ['technique.id'], ),
    sa.ForeignKeyConstraint(['tactic_id'], ['tactic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tactic_default_mapping_capability',
    sa.Column('tactic_id', sa.String(length=64), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capability.id'], ),
    sa.ForeignKeyConstraint(['tactic_id'], ['tactic_default_mapping.tactic_id'], ),
    sa.PrimaryKeyConstraint('tactic_id', 'capability_id')
    )
    op.create_table('tactic_default_mapping_control',
    sa.Column('tactic_id', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['control.id'], ),
    sa.ForeignKeyConstraint(['tactic_id'], ['tactic_default_mapping.tactic_id'], ),
    sa.PrimaryKeyConstraint('tactic_id', 'control_id')
    )
    op.create_table('technique_capability_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('technique_id', sa.String(length=16), nullable=False),
    sa.Column('mapping_source', sa.Enum('SPECIFIC', 'TACTIC_DEFAULT', name='mapping_source'), nullable=False),
    sa.Column('impact', sa.Enum('NIEDRIG', 'MITTEL', 'HOCH', 'SEHR_HOCH', name='impact_level'), nullable=False),
    sa.Column('effort', sa.Enum('NIEDRIG', 'MITTEL', 'HOCH', name='effort_level'), nullable=False),
    sa.ForeignKeyConstraint(['technique_id'], ['technique.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technique_id', name='uq_mapping_technique')
    )
    op.create_table('technique_capability_mapping_capability',
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capability.id'], ),
    sa.ForeignKeyConstraint(['mapping_id'], ['technique_capability_mapping.id'], ),
    sa.PrimaryKeyConstraint('mapping_id', 'capability_id')
    )
    op.create_table('technique_capability_mapping_control',
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['control.id'], ),
    sa.ForeignKeyConstraint(['mapping_id'], ['technique_capability_mapping.id'], ),
    sa.PrimaryKeyConstraint('mapping_id', 'control_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technique_capability_mapping_control')
    op.drop_table('technique_capability_mapping_capability')
    op.drop_table('technique_capability_mapping')
    op.drop_table('tactic_default_mapping_control')
    op.drop_table('tactic_default_mapping_capability')
    op.drop_table('technique')
    op.drop_table('tactic_default_mapping')
    op.drop_table('tactic')
    op.drop_table('control')
    op.drop_table('capability')
    # ### end Alembic commands ###
