"""add portfolio_technology tables

Revision ID: 992e2daddd85
Revises: 29e729bcbe92
Create Date: 2026-08-31 06:54:08.217745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992e2daddd85'
down_revision: Union[str, Sequence[str], None] = '29e729bcbe92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_technology',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_technology_capability',
    sa.Column('portfolio_technology_id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capability.id'], ),
    sa.ForeignKeyConstraint(['portfolio_technology_id'], ['portfolio_technology.id'], ),
    sa.PrimaryKeyConstraint('portfolio_technology_id', 'capability_id')
    )
    op.create_table('portfolio_technology_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_technology_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.String(length=128), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('field_changed', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.String(length=1024), nullable=True),
    sa.Column('new_value', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_technology_id'], ['portfolio_technology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_technology_history')
    op.drop_table('portfolio_technology_capability')
    op.drop_table('portfolio_technology')
    # ### end Alembic commands ###
