/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Codes
         * @description Zustandslose Analyse: T-Nummern rein, priorisierte Maßnahmen raus.
         *     Deckt den Analyzer-Tab ab, der im Prototyp ohne Engagement-Bindung
         *     funktioniert (docs/projektauftrag.md Abschnitt 10a.5).
         */
        post: operations["analyze_codes_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engagements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Engagements */
        get: operations["list_engagements_api_engagements_get"];
        put?: never;
        /** Create Engagement */
        post: operations["create_engagement_api_engagements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engagements/{engagement_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Findings
         * @description Fügt T-Nummern als Findings zu einem Engagement hinzu. Codes, die nicht
         *     im Techniken-Katalog existieren, werden nicht persistiert (die finding-
         *     Tabelle referenziert technique_id per Fremdschlüssel) und stattdessen
         *     sichtbar als unknown_codes zurückgegeben (Abschnitt 10a.5).
         */
        post: operations["add_findings_api_engagements__engagement_id__findings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engagements/{engagement_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Engagement Analysis
         * @description Berechnet das AnalyzerResult zur Laufzeit aus den finding-Zeilen des
         *     Engagements — keine materialisierte recommendation-Tabelle (bewusste
         *     Entscheidung, Abschnitt 10a.1).
         */
        get: operations["get_engagement_analysis_api_engagements__engagement_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/techniques": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Techniques
         * @description Techniken-Katalog mit Mapping-Status je Technik, für den 'Alle
         *     Techniken'-Tab (docs/projektauftrag.md Abschnitt 10b.1). `tactic` filtert
         *     nach Taktik-Name, `status` nach 'specific'/'tactic_default', `q` durchsucht
         *     Technik-ID und -Name (case-insensitive).
         */
        get: operations["get_techniques_api_techniques_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/technologies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Technologies */
        get: operations["get_technologies_api_portfolio_technologies_get"];
        put?: never;
        /** Post Technology */
        post: operations["post_technology_api_portfolio_technologies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/technologies/{technology_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Technology */
        patch: operations["patch_technology_api_portfolio_technologies__technology_id__patch"];
        trace?: never;
    };
    "/api/portfolio/technologies/{technology_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Deactivate Technology */
        post: operations["post_deactivate_technology_api_portfolio_technologies__technology_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/technologies/{technology_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Technology History */
        get: operations["get_technology_history_api_portfolio_technologies__technology_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Coverage */
        get: operations["get_coverage_api_portfolio_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Capabilities
         * @description Referenzliste aller Capabilities mit ID — nötig für die Capability-
         *     Mehrfachauswahl im Portfolio-Formular (docs/projektauftrag.md Abschnitt
         *     10c.5), da die Coverage-Antwort nur Namen liefert, keine IDs.
         */
        get: operations["get_capabilities_api_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Codes */
            codes: string;
        };
        /** AnalyzerResult */
        AnalyzerResult: {
            /** Input Codes */
            input_codes: string[];
            /** Techniques */
            techniques: components["schemas"]["TechniqueResult"][];
            /** Unknown Codes */
            unknown_codes: string[];
            /** Prioritized Measures */
            prioritized_measures: components["schemas"]["PrioritizedMeasure"][];
        };
        /** CapabilityRead */
        CapabilityRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** ControlRef */
        ControlRef: {
            /** Id */
            id: number;
            /**
             * Category
             * @enum {string}
             */
            category: "prevent" | "detect" | "respond";
            /** Label */
            label: string;
        };
        /** CoverageResult */
        CoverageResult: {
            /** Rows */
            rows: components["schemas"]["CoverageRow"][];
            /** Gaps */
            gaps: string[];
        };
        /** CoverageRow */
        CoverageRow: {
            /** Capability */
            capability: string;
            /** Covering Technologies */
            covering_technologies: string[];
        };
        /** EngagementCreate */
        EngagementCreate: {
            /** Name */
            name: string;
            /** External Ref */
            external_ref?: string | null;
        };
        /** EngagementRead */
        EngagementRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** External Ref */
            external_ref: string | null;
            /** Status */
            status: string;
        };
        /** FindingsCreate */
        FindingsCreate: {
            /** Codes */
            codes: string;
        };
        /** FindingsCreateResult */
        FindingsCreateResult: {
            /** Added Technique Ids */
            added_technique_ids: string[];
            /** Unknown Codes */
            unknown_codes: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PortfolioTechnologyCreate */
        PortfolioTechnologyCreate: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Capability Ids
             * @default []
             */
            capability_ids: number[];
        };
        /** PortfolioTechnologyHistoryEntry */
        PortfolioTechnologyHistoryEntry: {
            /** Id */
            id: number;
            /** Changed By */
            changed_by: string | null;
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
            /** Field Changed */
            field_changed: string;
            /** Old Value */
            old_value: string | null;
            /** New Value */
            new_value: string | null;
        };
        /** PortfolioTechnologyRead */
        PortfolioTechnologyRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Active */
            active: boolean;
            /** Capabilities */
            capabilities: string[];
        };
        /**
         * PortfolioTechnologyUpdate
         * @description Alle Felder optional (PATCH-Semantik) — nur mitgeschickte Felder werden
         *     geändert und lösen jeweils einen eigenen History-Eintrag aus.
         */
        PortfolioTechnologyUpdate: {
            /** Name */
            name?: string | null;
            /** Type */
            type?: string | null;
            /** Capability Ids */
            capability_ids?: number[] | null;
        };
        /** PrioritizedMeasure */
        PrioritizedMeasure: {
            /** Control Id */
            control_id: number;
            /**
             * Category
             * @enum {string}
             */
            category: "prevent" | "detect" | "respond";
            /** Label */
            label: string;
            /** Priority Rank */
            priority_rank: number;
            /** Chain Coverage Count */
            chain_coverage_count: number;
            /** Affected Technique Ids */
            affected_technique_ids: string[];
        };
        /** TechniqueCatalogResult */
        TechniqueCatalogResult: {
            /** Techniques */
            techniques: components["schemas"]["TechniqueSummary"][];
            /** Total */
            total: number;
        };
        /** TechniqueResult */
        TechniqueResult: {
            /** Technique Id */
            technique_id: string;
            /** Technique Name */
            technique_name: string;
            /** Tactic Name */
            tactic_name: string;
            /**
             * Mapping Source
             * @enum {string}
             */
            mapping_source: "specific" | "tactic_default";
            /** Resolved Via Technique Id */
            resolved_via_technique_id: string | null;
            /**
             * Impact
             * @enum {string}
             */
            impact: "niedrig" | "mittel" | "hoch" | "sehr_hoch";
            /**
             * Effort
             * @enum {string}
             */
            effort: "niedrig" | "mittel" | "hoch";
            /** Capabilities */
            capabilities: string[];
            /** Controls */
            controls: components["schemas"]["ControlRef"][];
            /**
             * Portfolio Fit
             * @default []
             */
            portfolio_fit: string[];
        };
        /** TechniqueSummary */
        TechniqueSummary: {
            /** Technique Id */
            technique_id: string;
            /** Technique Name */
            technique_name: string;
            /** Tactic Name */
            tactic_name: string;
            /**
             * Mapping Source
             * @enum {string}
             */
            mapping_source: "specific" | "tactic_default";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    analyze_codes_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzerResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_engagements_api_engagements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngagementRead"][];
                };
            };
        };
    };
    create_engagement_api_engagements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EngagementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngagementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_findings_api_engagements__engagement_id__findings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engagement_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingsCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingsCreateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_engagement_analysis_api_engagements__engagement_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engagement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzerResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_techniques_api_techniques_get: {
        parameters: {
            query?: {
                tactic?: string | null;
                status?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechniqueCatalogResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_technologies_api_portfolio_technologies_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioTechnologyRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_technology_api_portfolio_technologies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioTechnologyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioTechnologyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_technology_api_portfolio_technologies__technology_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technology_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioTechnologyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioTechnologyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_deactivate_technology_api_portfolio_technologies__technology_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technology_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioTechnologyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_technology_history_api_portfolio_technologies__technology_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technology_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioTechnologyHistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coverage_api_portfolio_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageResult"];
                };
            };
        };
    };
    get_capabilities_api_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityRead"][];
                };
            };
        };
    };
}
